# Write your MySQL query statement
SELECT DISTINCT visited_on,
SUM(amount) OVER (ORDER BY visited_on ASC RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW) AS amount,
ROUND(SUM(amount) OVER (ORDER BY visited_on ASC RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW)/7, 2) AS average_amount
FROM Customer
LIMIT 100000000
OFFSET 6
